export const topics = [
  { label: "All", value: "All" },
  { label: "Catnip", value: "Catnip" },
  { label: "No Code", value: "No Code" },
  { label: "Design", value: "Design" },
  { label: "Partner Up", value: "Partner Up" },
  { label: "Community Building", value: "Community Building" },
  { label: "Product Management", value: "Product Management" },
  { label: "Side Project", value: "Side Project" },
  { label: "Recommendations", value: "Recommendations" },
  { label: "Ideas and Validation", value: "Ideas and Validation" },
  { label: "Development", value: "Development" },
  { label: "Time Management", value: "Time Management" },
  { label: "Growth", value: "Growth" },
  { label: "Remote Working", value: "Remote Working" },
  { label: "Marketing and SEO", value: "Marketing and SEO" },
  { label: "Makers Mindset", value: "Makers Mindset" },
  { label: "Building in Public", value: "Building in Public" },
  { label: "Launch Tips", value: "Launch Tips" },
  { label: "Success and Failure", value: "Success and Failure" },
  { label: "Feedback", value: "Feedback" },
];
